### ISSUE TITLE
Paleta de cores muda condicionalmente, light mode deixa cores erradas nos icones e textos brancos.

### ISSUE THREAD

**Issue by jusqua** [softeam-org/sibragectic-front#19]
![Screenshot_20230305-091449_Chrome.png](https://user-images.githubusercontent.com/62023311/222959914-69b659ff-119a-4146-ae7b-d92f38c38d59.png)

![Screenshot_20230305-091434_Chrome.png](https://user-images.githubusercontent.com/62023311/222959913-4724e19a-12fc-4f3b-ac75-7c27edbd541e.png)

**Comment by Luiz-Fel** [comment]
Alterei pro header

**Comment by jusqua** [comment]
Verificado

**Comment by jusqua** [comment]
Paleta de cores ainda está errada nos submenus do header
