### ISSUE TITLE
Colocar botão explícito para os templates

### ISSUE THREAD

**Issue by jusqua** [softeam-org/sibragectic-front#25]
![IMG-20230305-WA0012.jpg](https://user-images.githubusercontent.com/62023311/222983345-6160536b-b949-4d8d-b928-be9006a44501.jpg)

Adicionar texto:
"Há dois templates dos artigos, um para o SIBRAGEC e outro para o SBTIC"
Botão "Clique aqui para acessar"

**Comment by Luiz-Fel** [comment]
![Image](https://user-images.githubusercontent.com/36901019/223144774-a57967dc-f0ac-48ae-ab81-d6932b9e19ae.png)

Botões adicionados
