### ISSUE TITLE
Adição de texto

### ISSUE THREAD

**Issue by fnguedes** [softeam-org/sibragectic-front#51]
Na página de submissões é necessário adicionar acima da tabela do calendário o seguinte texto : "ATENÇÃO! Prorrogado o prazo de submissão para artigos compactos. Confira as novas datas abaixo."

**Comment by Luiz-Fel** [comment]
![Image](https://user-images.githubusercontent.com/36901019/230398906-9034d8bc-17b6-4d81-97df-dbcd8d4acd1f.png)
